language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost-dev libboost-test-dev
script:
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-std=c++0x"
  - make
  - make test
