language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libboost1.48-dev libboost-test1.48-dev
script:
  - git clone https://github.com/boostorg/metaparse.git
  - mv metaparse/include/boost .
  - rm -rf metaparse
  - mkdir bin
  - cd bin
  - cmake .. -DCMAKE_CXX_FLAGS:STRING="-std=c++0x"
  - make
  - make test
  - cd ..
  - rm -rf bin
  - mkdir bin
  - cd bin
  - cmake ..
  - make
  - make test
